COCO = ('person,child,girl,boy,woman,man,people,children,girls,boys,women,men,lady,guy,ladies,guys,clothes',
        'bicycle,bicycles,bike,bikes', 'car,cars', 'motorcycle,motorcycles', 'airplane,airplanes', 'bus,buses',
        'train,trains,locomotive,locomotives,freight train', 'truck,trucks', 'boat,boats', 'traffic light',
        'fire hydrant', 'stop sign', 'parking meter', 'bench,benches', 'bird,birds', 'cat,cats,kitties,kitty',
        'dog,dogs,puppy,puppies', 'horse,horses,foal', 'sheep', 'cow,cows,calf', 'elephant,elephants', 'bear,bears',
        'zebra,zebras', 'giraffe,giraffes', 'backpack,backpacks', 'umbrella,umbrellas', 'handbag,handbags', 'tie',
        'suitcase,suitcases', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite,kites', 'baseball bat',
        'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle,bottles,water bottle',
        'wine glass,wine glasses,wineglass', 'cup,cups,water cup,water glass', 'fork,forks', 'knife,knives',
        'spoon,spoons', 'bowl,bowls', 'banana,bananas', 'apple,apples,apple fruit', 'sandwich,sandwiches',
        'orange fruit', 'broccoli', 'carrot,carrots', 'hot dog', 'pizza', 'donut,donuts', 'cake,cakes', 'chair,chairs',
        'couch,sofa,sofas', 'potted plant,potted plants,pottedplant,pottedplants,planter,planters', 'bed,beds',
        'dining table,dining tables,diningtable,diningtables,plate,plates,diningtable tablecloth', 'toilet', 'tv',
        'laptop', 'mouse', 'tv remote,remote control', 'keyboard', 'cell phone,mobile', 'microwave', 'oven,ovens',
        'toaster', 'sink,sinks', 'refrigerator,fridge', 'book,books', 'clock', 'vase,vases', 'scissor,scissors',
        'teddy bear,teddy bears', 'hair drier', 'toothbrush,toothbrushes', 'banner,banners', 'blanket,blankets',
        'bridge', 'cardboard', 'counter', 'curtain,curtains', 'door,doors', 'wood floor', 'flower,flowers',
        'fruit,fruits', 'gravel', 'house', 'lamp,bulb,lamps,bulbs', 'mirror', 'tennis net', 'pillow,pillows',
        'platform', 'playingfield,tennis court,baseball field,soccer field,tennis field', 'railroad', 'river', 'road',
        'roof', 'sand', 'sea,sea wave,wave,waves', 'shelf', 'snow', 'stairs', 'tent', 'towel', 'brick wall',
        'stone wall', 'tile wall', 'wood wall', 'water', 'window blind', 'window', 'tree,trees,palm tree,bushes',
        'fence,fences', 'ceiling', 'sky,clouds', 'cabinet,cabinets', 'table', 'floor,flooring,tile floor', 'pavement',
        'mountain,mountains', 'grass', 'dirt', 'paper', 'food', 'building,buildings', 'rock', 'wall,walls', 'rug')
